// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package main

const (
	ApiKeyAdminScopes = "ApiKeyAdmin.Scopes"
	ApiKeyUserScopes  = "ApiKeyUser.Scopes"
	CookieAdminScopes = "CookieAdmin.Scopes"
	CookieUserScopes  = "CookieUser.Scopes"
)

// Apikey defines model for Apikey.
type Apikey struct {
	Id Id `json:"id"`
}

// Apikeys defines model for Apikeys.
type Apikeys struct {
	Items []Apikey `json:"items"`
}

// BadError defines model for BadError.
type BadError struct {
	Error int `json:"error"`
}

// DumpData defines model for DumpData.
type DumpData struct {
	Apikeys   *Apikeys   `json:"apikeys,omitempty"`
	Pets      *Pets      `json:"pets,omitempty"`
	Petstores *Petstores `json:"petstores,omitempty"`
	Sessions  *Sessions  `json:"sessions,omitempty"`
	Users     *Users     `json:"users,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Id defines model for Id.
type Id = string

// LoginData defines model for LoginData.
type LoginData struct {
	Password string   `json:"password"`
	User     Username `json:"user"`
}

// NewPet defines model for NewPet.
type NewPet struct {
	Age        int     `json:"age"`
	Name       PetName `json:"name"`
	PetstoreId Id      `json:"petstoreId"`
}

// NewPetstore defines model for NewPetstore.
type NewPetstore struct {
	Name PetstoreName `json:"name"`
}

// Pet defines model for Pet.
type Pet struct {
	Age        int      `json:"age"`
	Id         Id       `json:"id"`
	Name       PetName  `json:"name"`
	Owner      Username `json:"owner"`
	PetstoreId Id       `json:"petstoreId"`
}

// PetName defines model for PetName.
type PetName = string

// Pets defines model for Pets.
type Pets struct {
	Items []Pet `json:"items"`
}

// Petstore defines model for Petstore.
type Petstore struct {
	Id   Id           `json:"id"`
	Name PetstoreName `json:"name"`
}

// PetstoreName defines model for PetstoreName.
type PetstoreName = string

// Petstores defines model for Petstores.
type Petstores struct {
	Items []Petstore `json:"items"`
}

// Session defines model for Session.
type Session struct {
	Id Id `json:"id"`
}

// Sessions defines model for Sessions.
type Sessions struct {
	Items []Session `json:"items"`
}

// User defines model for User.
type User struct {
	IsAdmin  bool     `json:"isAdmin"`
	Password string   `json:"password"`
	User     Username `json:"user"`
}

// Username defines model for Username.
type Username = string

// Users defines model for Users.
type Users struct {
	Items []User `json:"items"`
}

// Version defines model for Version.
type Version struct {
	CommitId string `json:"commitId"`
	Version  string `json:"version"`
}

// PathId defines model for PathId.
type PathId = Id

// PathUsername defines model for PathUsername.
type PathUsername = Username

// N400 defines model for 400.
type N400 struct {
	Message string `json:"message"`
}

// N401 defines model for 401.
type N401 = Error

// Default defines model for default.
type Default = Error

// TransferPetJSONBody defines parameters for TransferPet.
type TransferPetJSONBody struct {
	PetstoreId Id `json:"petstoreId"`
}

// FindPetstoresParams defines parameters for FindPetstores.
type FindPetstoresParams struct {
	// Name name to filter by
	Name *PetstoreName `form:"name,omitempty" json:"name,omitempty"`

	// Limit maximum number of results to return
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// BadErrorJSONRequestBody defines body for BadError for application/json ContentType.
type BadErrorJSONRequestBody = BadError

// UserLoginJSONRequestBody defines body for UserLogin for application/json ContentType.
type UserLoginJSONRequestBody = LoginData

// UserLoginUrlencodedFormdataRequestBody defines body for UserLoginUrlencoded for application/x-www-form-urlencoded ContentType.
type UserLoginUrlencodedFormdataRequestBody = LoginData

// CreatePetJSONRequestBody defines body for CreatePet for application/json ContentType.
type CreatePetJSONRequestBody = NewPet

// TransferPetJSONRequestBody defines body for TransferPet for application/json ContentType.
type TransferPetJSONRequestBody TransferPetJSONBody

// CreatePetstoreJSONRequestBody defines body for CreatePetstore for application/json ContentType.
type CreatePetstoreJSONRequestBody = NewPetstore

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = User
